baseURL = 'https://aatmunbaxi.netlify.app'
languageCode = 'en-us'
title = 'Aatmun Baxi'
theme = 'archie'


[params]
  mode = "light"
  ShowWordCount = true
  customcss =["css/main.css"]
  mathjax = true


[markup.goldmark.renderer]
  unsafe = true

[markup]
  [markup.highlight]
       guessSyntax = false
       style = "emacs"
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]']]
          inline = [['\(', '\)']]
