baseURL = 'https://aatmunbaxi.netlify.app'
languageCode = 'en-us'
title = 'Aatmun Baxi'
theme = 'PaperMod'

[taxonomies]
  category = "computing"
  tag = "tags"
  series = "series"
[author]
  name = "Aatmun Baxi"
[params]
  ShowWordCount = true
  custom_css =["style.css"]

[markup.highlight]
  style = "paraiso-dark"

[markup.goldmark.renderer]
  unsafe = true
