baseURL = 'https://aatmunbaxi.netlify.app'
languageCode = 'en-us'
title = 'Aatmun Baxi'
theme = 'PaperMod'

disableThemeToggle = true

[params]
  defaultTheme = "dark"
  disableThemeToggle = true
  ShowWordCount = true

[markup.goldmark.renderer]
  unsafe = true
