baseURL = 'https://aatmunbaxi.netlify.app'
languageCode = 'en-us'
title = 'Aatmun Baxi'
theme = 'archie'

[params]
  customcss = ["css/modus_style.css"]
  mode = "light"
  ShowWordCount = true
  mathjax = true
[taxonomies]
  tag = "tag"


[markup.goldmark.renderer]
  unsafe = true

[markup]

  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]']]
          inline = [['\(', '\)']]
